language: node_js

node_js: node

cache: npm

services:
  - docker

script:
  - npm test
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - docker build . -t devisv/react-ci-test:dev --no-cache
  - docker push devisv/react-ci-test:dev