language: node_js

node_js: node

cache: npm

addons:
  apt:
    packages:
      - sshpass

services:
  - docker

script:
  - npm test
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - docker build . -t devisv/react-ci-test:dev --no-cache
  - docker push devisv/react-ci-test:dev
  - sshpass -p $SERVER_PASSWORD ssh -o StrictHostKeyChecking=no $SERVER_LOGIN@176.57.68.182 'docker stop $(docker ps -a -q)'